[build]
  command = "CI= npm run build"
  publish = "build"

[build.environment]
  CI = ""
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Service Worker - Never cache (critical for updates)
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# Static JS/CSS - Cache for 1 year (performance)
[[headers]]
  for = "/static/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Manifest - Cache for 1 day
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Your existing CSP and other headers
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.sanity.io https://www.googletagmanager.com https://cdn.onesignal.com https://onesignal.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.onesignal.com https://onesignal.com;
      font-src 'self' https://fonts.gstatic.com;
      img-src 'self' https://res.cloudinary.com https://cdn.sanity.io https://onesignal.com https://img.onesignal.com data: blob:;
      media-src 'self' https://res.cloudinary.com blob:;
      connect-src 'self' https://*.sanity.io https://cdn.sanity.io https://sologram-api.onrender.com https://cdn.onesignal.com https://onesignal.com https://api2.onesignal.com wss://*.onesignal.com https://www.google-analytics.com https://api.cloudinary.com;
      frame-src 'self' https://onesignal.com;
    """