[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'nonce-abc123' https://cdn.sanity.io https://www.googletagmanager.com https://cdn.onesignal.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com;
      img-src 'self' https://res.cloudinary.com data: blob:;
      media-src 'self' https://res.cloudinary.com blob:;
      connect-src 'self' https://sologram-api.onrender.com https://cdn.onesignal.com https://www.google-analytics.com https://api.cloudinary.com;
      frame-src 'self';
    """
